var AdminDispatcher = require('../dispatcher/AdminDispatcher');
var AdminConstants = require('../constants/AdminConstants');

var ActionTypes = AdminConstants.ActionTypes;

module.exports = {
  	receivedMessageData:function(res){
		AdminDispatcher.dispatch({
			type: ActionTypes.RECEIVED_MESSAGE,
			data: res
		});
	},
	receivedSchoolList:function(res){
		AdminDispatcher.dispatch({
			type:ActionTypes.RECEIVED_SCHOOLLIST,
			data:res
		});
	},
	postedSchoolForm:function(res){
		AdminDispatcher.dispatch({
			type:ActionTypes.POSTED_SCHOOLFORM,
			data:res
		});
	},
	deletedSchoolForm:function(res){
		AdminDispatcher.dispatch({
			type:ActionTypes.DELETED_SCHOOLFORM,
			data:res
		});
	},
	putedSchoolForm:function(res){
		AdminDispatcher.dispatch({
			type:ActionTypes.PUTED_SCHOOLFORM,
			data:res
		});
	},
	receivedSchoolAdminList:function(res){
		AdminDispatcher.dispatch({
			type:ActionTypes.RECEIVED_SCHOOLADMINLIST,
			data:res
		});
	},
	postedSchoolAdminForm:function(res){
		AdminDispatcher.dispatch({
			type:ActionTypes.POSTED_SCHOOLADMINFORM,
			data:res
		});
	},
	deletedSchoolAdminUser:function(res){
		AdminDispatcher.dispatch({
			type:ActionTypes.DELETED_SCHOOLADMINUSER,
			data:res
		});
	},
	putedSchoolAdminUser:function(res){
		AdminDispatcher.dispatch({
			type:ActionTypes.PUTED_SCHOOLADMINUSER,
			data:res
		});
	},
	receivedSuperAdminList:function(res){
		AdminDispatcher.dispatch({
			type:ActionTypes.RECEIVED_SUPERADMINLIST,
			data:res
		});
	},
	postedSuperAdminForm:function(res){
		AdminDispatcher.dispatch({
			type:ActionTypes.POSTED_SUPERADMINFORM,
			data:res
		});
	},
	deletedSuperAdminUser:function(res){
		AdminDispatcher.dispatch({
			type:ActionTypes.DELETED_SUPERADMINUSER,
			data:res
		});
	},
	putedSuperAdminUser:function(res){
		AdminDispatcher.dispatch({
			type:ActionTypes.PUTED_SUPERADMINUSER,
			data:res
		});
	},
	receivedSubjectList:function(res){
		AdminDispatcher.dispatch({
			type:ActionTypes.RECEIVED_SUBJECTLIST,
			data:res
		});
	},
	postedSubjectForm:function(res){
		AdminDispatcher.dispatch({
			type:ActionTypes.POSTED_SUBJECTFORM,
			data:res
		});
	},
	deletedSubjectForm:function(res){
		AdminDispatcher.dispatch({
			type:ActionTypes.DELETED_SUBJECTFORM,
			data:res
		});
	},
	putedSubjectForm:function(res){
		AdminDispatcher.dispatch({
			type:ActionTypes.PUTED_SUBJECTFORM,
			data:res
		});
	},
	receivedGradeList:function(res){
		AdminDispatcher.dispatch({
			type:ActionTypes.RECEIVED_GRADELIST,
			data:res
		});
	},
	postedGradeForm:function(res){
		AdminDispatcher.dispatch({
			type:ActionTypes.POSTED_GRADEFORM,
			data:res
		});
	},
	deletedGradeForm:function(res){
		AdminDispatcher.dispatch({
			type:ActionTypes.DELETED_GRADEFORM,
			data:res
		});
	},
	putedGradeForm:function(res){
		AdminDispatcher.dispatch({
			type:ActionTypes.PUTED_GRADEFORM,
			data:res
		});
	},
	receivedPublishList:function(res){
		AdminDispatcher.dispatch({
			type:ActionTypes.RECEIVED_PUBLISHLIST,
			data:res
		});
	},
	postedPublishForm:function(res){
		AdminDispatcher.dispatch({
			type:ActionTypes.POSTED_PUBLISHFORM,
			data:res
		});
	},
	deletedPublishForm:function(res){
		AdminDispatcher.dispatch({
			type:ActionTypes.DELETED_PUBLISHFORM,
			data:res
		});
	},
	putedPublishForm:function(res){
		AdminDispatcher.dispatch({
			type:ActionTypes.PUTED_PUBLISHFORM,
			data:res
		});
	},
	receivedVersionList:function(res){
		AdminDispatcher.dispatch({
			type:ActionTypes.RECEIVED_VERSIONLIST,
			data:res
		});
	},
	postedVersionForm:function(res){
		AdminDispatcher.dispatch({
			type:ActionTypes.POSTED_VERSIONFORM,
			data:res
		});
	},
	deletedVersionForm:function(res){
		AdminDispatcher.dispatch({
			type:ActionTypes.DELETED_VERSIONFORM,
			data:res
		});
	},
	putedVersionForm:function(res){
		AdminDispatcher.dispatch({
			type:ActionTypes.PUTED_VERSIONFORM,
			data:res
		});
	},
	receivedVersionNodeList:function(res){
		AdminDispatcher.dispatch({
			type:ActionTypes.RECEIVED_VERSIONNODELIST,
			data:res
		});
	},
	postedVersionNodeForm:function(res){
		AdminDispatcher.dispatch({
			type:ActionTypes.POSTED_VERSIONNODEFORM,
			data:res
		});
	},
	deletedVersionNodeForm:function(res){
		AdminDispatcher.dispatch({
			type:ActionTypes.DELETED_VERSIONNODEFORM,
			data:res
		});
	},
	putedVersionNodeForm:function(res){
		AdminDispatcher.dispatch({
			type:ActionTypes.PUTED_VERSIONNODEFORM,
			data:res
		});
	},  

};