var AdminActionCreators = require('../actions/AdminActionCreators');

var DefulatAjaxMsg ={
    success:"成功",
    error:"失败",
    warn:"服务器错误"
}
var Ajax = function(options){
          $.ajax({ url:options.url, type: options.type, dataType: "json", data: options.data,
            success: function(res){
                if (res.status == "success"){
                            if(options.msg && options.msg.success){ 
                                    AdminActionCreators.receivedMessageData({
                                            status:res.status.toUpperCase(),
                                            content:"成功"
                                    });
                            }
                            if(options.success) options.success(res);
                }else{
                            if(options.msg && options.msg.error){ 
                                AdminActionCreators.receivedMessageData({
                                        status:res.status.toUpperCase(),
                                        content:"失败"
                                });
                            }
                            if(options.error) options.error("error",res.data,res.msg);
                }
            },
            error: function(e, err){
                if(options.msg && options.msg.warn){
                    AdminActionCreators.receivedMessageData({
                            status:"warning".toUpperCase(),
                            content:"服务器错误"
                    });
                }
                 if(options.error) options.error("warning",e,err);
            }
          })
}

module.exports = {
    /*获取所有学校*/
    getSchoolList:function(){
        Ajax({
            url:"/api/v2/admin/school",
            type:"get",
            success:function(res){
                AdminActionCreators.receivedSchoolList(res.data);
            },
            msg:DefulatAjaxMsg
        })
    },
    /*新增学校*/
    postSchoolForm:function(formdata){
        Ajax({
            url:"/api/v2/admin/school",
            type:"post",
            data:formdata,
            success:function(res){
                AdminActionCreators.postedSchoolForm(res.data);
                this.getSchoolList();
            }.bind(this),
            msg:DefulatAjaxMsg
        })
    },
     /*删除学校*/
    deleteSchoolForm:function(school_id){
        Ajax({
            url:"/api/v2/admin/school?school_id="+school_id,
            type:"delete",
            success:function(res){
                AdminActionCreators.deletedSchoolForm(res.data);
                this.getSchoolList();
            }.bind(this),
            msg:DefulatAjaxMsg
        })
    },
     /*修改学校*/
    putSchoolForm:function(formdata){
        Ajax({
            url:"/api/v2/admin/school",
            type:"put",
            data:formdata,
            success:function(res){
                AdminActionCreators.putedSchoolForm(res.data);
                this.getSchoolList();
            }.bind(this),
            msg:DefulatAjaxMsg
        })
    },
    /*获取所有学校管理员用户*/
    getSchoolAdminList:function(school_id){
        var url = "";
        (school_id && (url="?school_id="+school_id))
        Ajax({
            url:"/api/v2/admin/school_admin"+url,
            type:"get",
            success:function(res){
                AdminActionCreators.receivedSchoolAdminList(res.data);
            },
            msg:DefulatAjaxMsg
        })
    },
    /*新增学校管理员用户*/
    postSchoolAdminForm:function(formdata){
        Ajax({
            url:"/api/v2/admin/school_admin",
            type:"post",
            data:formdata,
            success:function(res){
                AdminActionCreators.postedSchoolAdminForm(res.data);
                this.getSchoolAdminList(formdata.school_id);
            }.bind(this),
            msg:DefulatAjaxMsg
        })
    },   
    /*删除学校管理员用户*/
    deleteSchoolAdminUser:function(user_id,school_id){
        Ajax({
            url:"/api/v2/admin/school_admin?user_id="+user_id,
            type:"delete",
            success:function(res){
                AdminActionCreators.deletedSchoolAdminUser(res.data);
                this.getSchoolAdminList(school_id);
            }.bind(this),
            msg:DefulatAjaxMsg
        })
    },  
    /*修改学校管理员用户*/
    putSchoolAdminUser:function(formdata){
        Ajax({
            url:"/api/v2/admin/school_admin",
            type:"put",
            data:formdata,
            success:function(res){
                AdminActionCreators.putedSchoolAdminUser(res.data);
                this.getSchoolAdminList(formdata.school_id);
            }.bind(this),
            msg:DefulatAjaxMsg
        })
    },       
    /*获取超级后台所有超级管理员用户*/
    getSuperAdminList:function(school_id){
        var url = "";
        (school_id && (url="?school_id="+school_id))
        Ajax({
            url:"/api/v2/admin/super_admin"+url,
            type:"get",
            success:function(res){
                AdminActionCreators.receivedSuperAdminList(res.data);
            },
            msg:DefulatAjaxMsg
        })
    },
    /*新增超级管理员用户*/
    postSuperAdminForm:function(formdata){
        Ajax({
            url:"/api/v2/admin/super_admin",
            type:"post",
            data:formdata,
            success:function(res){
                AdminActionCreators.postedSuperAdminForm(res.data);
            },
            msg:DefulatAjaxMsg
        })
    },   
    /*删除学校管理员用户*/
    deleteSuperAdminUser:function(user_id){
        Ajax({
            url:"/api/v2/admin/super_admin?user_id="+user_id,
            type:"delete",
            success:function(res){
                AdminActionCreators.deletedSuperAdminUser(res.data);
            },
            msg:DefulatAjaxMsg
        })
    },  
    /*修改学校管理员用户*/
    putSuperAdminUser:function(formdata){
        Ajax({
            url:"/api/v2/admin/super_admin",
            type:"put",
            data:formdata,
            success:function(res){
                AdminActionCreators.putedSuperAdminUser(res.data);
            },
            msg:DefulatAjaxMsg
        })
    },         

    /*获取超级后台所有科目列表*/
    getSubjectList:function(){
        Ajax({
            url:"/api/v2/admin/subject",
            type:"get",
            success:function(res){
                AdminActionCreators.receivedSubjectList(res.data);
            },
            msg:DefulatAjaxMsg
        })
    },
    /*新增超级后台所有科目列表*/
    postSubjectForm:function(formdata){
        Ajax({
            url:"/api/v2/admin/subject",
            type:"post",
            data:formdata,
            success:function(res){
                AdminActionCreators.postedSubjectForm(res.data);
                this.getSubjectList();
            }.bind(this),
            msg:DefulatAjaxMsg
        })
    },   
    /*删除科目*/
    deleteSubjectForm:function(subject_id){
        Ajax({
            url:"/api/v2/admin/subject?subject_id="+subject_id,
            type:"delete",
            success:function(res){
                AdminActionCreators.deletedSubjectForm(res.data);
              this.getSubjectList();
            }.bind(this),
            msg:DefulatAjaxMsg
        })
    },  
    /*修改科目*/
    putSubjectForm:function(formdata){
        Ajax({
            url:"/api/v2/admin/subject",
            type:"put",
            data:formdata,
            success:function(res){
                AdminActionCreators.putedSubjectForm(res.data);
              this.getSubjectList();
            }.bind(this),
            msg:DefulatAjaxMsg
        })
    },   

    /*获取所有年级*/
    getGradeList:function(){
        Ajax({
            url:"/api/v2/admin/grade",
            type:"get",
            success:function(res){
                AdminActionCreators.receivedGradeList(res.data);
            },
            msg:DefulatAjaxMsg
        })
    },
    /*新增年级*/
    postGradeForm:function(formdata){
        Ajax({
            url:"/api/v2/admin/grade",
            type:"post",
            data:formdata,
            success:function(res){
                AdminActionCreators.postedGradeForm(res.data);
                this.getGradeList();
            }.bind(this),
            msg:DefulatAjaxMsg
        })
    },   
    /*删除年级*/
    deleteGradeForm:function(grade_id){
        Ajax({
            url:"/api/v2/admin/grade?grade_id="+grade_id,
            type:"delete",
            success:function(res){
                AdminActionCreators.deletedGradeForm(res.data);
              this.getGradeList();
            }.bind(this),
            msg:DefulatAjaxMsg
        })
    },  
    /*修改年级*/
    putGradeForm:function(formdata){
        Ajax({
            url:"/api/v2/admin/grade",
            type:"put",
            data:formdata,
            success:function(res){
                AdminActionCreators.putedGradeForm(res.data);
              this.getGradeList();
            }.bind(this),
            msg:DefulatAjaxMsg
        })
    },      

    /*获取所有出版社*/
    getPublishList:function(){
        Ajax({
            url:"/api/v2/admin/publish",
            type:"get",
            success:function(res){
                AdminActionCreators.receivedPublishList(res.data);
            },
            msg:DefulatAjaxMsg
        })
    },
    /*新增出版社*/
    postPublishForm:function(formdata){
        var updata = this.getPublishList;
        Ajax({
            url:"/api/v2/admin/publish",
            type:"post",
            data:formdata,
            success:function(res){
                AdminActionCreators.postedPublishForm(res.data);
                updata();
            },
            msg:DefulatAjaxMsg
        })
    },   
    /*删除出版社*/
    deletePublishForm:function(publish_id){
        var updata = this.getPublishList;
        Ajax({
            url:"/api/v2/admin/publish?publish_id="+publish_id,
            type:"delete",
            success:function(res){
                AdminActionCreators.deletedPublishForm(res.data);
                updata();
            },
            msg:DefulatAjaxMsg
        })
    },  
    /*修改出版社*/
    putPublishForm:function(formdata){
        var updata = this.getPublishList;
        Ajax({
            url:"/api/v2/admin/publish",
            type:"put",
            data:formdata,
            success:function(res){
                AdminActionCreators.putedPublishForm(res.data);
                updata();
            },
            msg:DefulatAjaxMsg
        })
    },    

    /*获取所有出版社*/
    getVersionList:function(){
        Ajax({
            url:"/api/v2/admin/version",
            type:"get",
            success:function(res){
                AdminActionCreators.receivedVersionList(res.data);
            },
            msg:DefulatAjaxMsg
        })
    },
    /*新增出版社*/
    postVersionForm:function(formdata){
        var update = this.getVersionList;
        Ajax({
            url:"/api/v2/admin/version",
            type:"post",
            data:formdata,
            success:function(res){
                AdminActionCreators.postedVersionForm(res.data);
                update();
            },
            msg:DefulatAjaxMsg
        })
    },   
    /*删除出版社*/
    deleteVersionForm:function(version_id){
        var update = this.getVersionList;
        Ajax({
            url:"/api/v2/admin/version?version_id="+version_id,
            type:"delete",
            success:function(res){
                AdminActionCreators.deletedVersionForm(res.data);
                update();
            },
            msg:DefulatAjaxMsg
        })
    },  
    /*修改出版社*/
    putVersionForm:function(formdata){
        var update = this.getVersionList;
        Ajax({
            url:"/api/v2/admin/version",
            type:"put",
            data:formdata,
            success:function(res){
                AdminActionCreators.putedVersionForm(res.data);
                update();
            },
            msg:DefulatAjaxMsg
        })
    },        
    /*获取科目信息*/
    

    /*获取所有知识点*/
    getVersionNodeList:function(formdata){
        Ajax({
            url:"/api/v2/admin/version_node",
            type:"get",
            data:formdata,
            success:function(res){
                AdminActionCreators.receivedVersionNodeList(res.data);
            },
            msg:DefulatAjaxMsg
        })
    },
    /*新增知识点*/
    postVersionNodeForm:function(formdata){
        var update = this.getVersionNodeList;
        Ajax({
            url:"/api/v2/admin/version_node",
            type:"post",
            data:formdata,
            success:function(res){
                AdminActionCreators.postedVersionNodeForm(res.data);
                update({"version_id":formdata.version_id});
            },
            msg:DefulatAjaxMsg
        })
    },   
    /*删除知识点*/
    deleteVersionNodeForm:function(version_node_id){
        var update = this.getVersionNodeList;
        Ajax({
            url:"/api/v2/admin/version_node?version_node_id="+version_node_id,
            type:"delete",
            success:function(res){
                AdminActionCreators.deletedVersionNodeForm(res.data);
                update({"version_id":version_node_id});
            },
            msg:DefulatAjaxMsg
        })
    },  
    /*修改知识点*/
    putVersionNodeForm:function(formdata){
        var update = this.getVersionNodeList;
        Ajax({
            url:"/api/v2/admin/version_node",
            type:"put",
            data:formdata,
            success:function(res){
                AdminActionCreators.putedVersionNodeForm(res.data);
                update({"version_id":formdata.version_id});
            },
            msg:DefulatAjaxMsg
        })
    },             
};
